# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-11 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_subtitle',
            field=models.IntegerField(null=True),
        ),
    ]
