# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-11 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_article_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_subtitle',
        ),
    ]
