# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_delete_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(null=True),
        ),
    ]
