# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20171115_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
