# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20171118_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-article_date']},
        ),
    ]
